/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue')['BButton']
    BCollapse: typeof import('bootstrap-vue')['BCollapse']
    BContainer: typeof import('bootstrap-vue')['BContainer']
    BDropdownForm: typeof import('bootstrap-vue')['BDropdownForm']
    BDropdownHeader: typeof import('bootstrap-vue')['BDropdownHeader']
    BFormCheckboxGroup: typeof import('bootstrap-vue')['BFormCheckboxGroup']
    BFormInput: typeof import('bootstrap-vue')['BFormInput']
    BNavbar: typeof import('bootstrap-vue')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue')['BNavForm']
    BNavItemDropdown: typeof import('bootstrap-vue')['BNavItemDropdown']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
