/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue')['BButton']
    BCard: typeof import('bootstrap-vue')['BCard']
    BCardBody: typeof import('bootstrap-vue')['BCardBody']
    BCardImg: typeof import('bootstrap-vue')['BCardImg']
    BCardImgLazy: typeof import('bootstrap-vue')['BCardImgLazy']
    BCardText: typeof import('bootstrap-vue')['BCardText']
    BCarousel: typeof import('bootstrap-vue')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue')['BCarouselSlide']
    BCol: typeof import('bootstrap-vue')['BCol']
    BCollapse: typeof import('bootstrap-vue')['BCollapse']
    BContainer: typeof import('bootstrap-vue')['BContainer']
    BDropdown: typeof import('bootstrap-vue')['BDropdown']
    BDropdownForm: typeof import('bootstrap-vue')['BDropdownForm']
    BDropdownHeader: typeof import('bootstrap-vue')['BDropdownHeader']
    BEmbed: typeof import('bootstrap-vue')['BEmbed']
    BForm: typeof import('bootstrap-vue')['BForm']
    BFormCheckboxGroup: typeof import('bootstrap-vue')['BFormCheckboxGroup']
    BFormDatepicker: typeof import('bootstrap-vue')['BFormDatepicker']
    BFormGroup: typeof import('bootstrap-vue')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue')['BFormInvalidFeedback']
    BFormRating: typeof import('bootstrap-vue')['BFormRating']
    BImg: typeof import('bootstrap-vue')['BImg']
    BModal: typeof import('bootstrap-vue')['BModal']
    BNavbar: typeof import('bootstrap-vue')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue')['BNavForm']
    BNavItemDropdown: typeof import('bootstrap-vue')['BNavItemDropdown']
    BPopover: typeof import('bootstrap-vue')['BPopover']
    BRow: typeof import('bootstrap-vue')['BRow']
    BTab: typeof import('bootstrap-vue')['BTab']
    BTabs: typeof import('bootstrap-vue')['BTabs']
    copy: typeof import('./src/components/HotelsSection copy.vue')['default']
    HotelCard: typeof import('./src/components/HotelCard.vue')['default']
    HotelCardRating: typeof import('./src/components/HotelCardRating.vue')['default']
    HotelCarousel: typeof import('./src/components/HotelCarousel.vue')['default']
    HotelsSection: typeof import('./src/components/HotelsSection.vue')['default']
    MapModal: typeof import('./src/components/modals/MapModal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PaymentCompleted: typeof import('./src/components/PaymentCompleted.vue')['default']
    PaymentForm: typeof import('./src/components/PaymentForm.vue')['default']
    PaymentLoading: typeof import('./src/components/PaymentLoading.vue')['default']
    PaymentModal: typeof import('./src/components/modals/PaymentModal.vue')['default']
    ReservationForm: typeof import('./src/components/ReservationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VisitorCounter: typeof import('./src/components/VisitorCounter.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBModal: typeof import('bootstrap-vue')['VBModal']
    vBTooltip: typeof import('bootstrap-vue')['VBTooltip']
  }
}
