/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue')['BButton']
    BCard: typeof import('bootstrap-vue')['BCard']
    BCardBody: typeof import('bootstrap-vue')['BCardBody']
    BCardImg: typeof import('bootstrap-vue')['BCardImg']
    BCardImgLazy: typeof import('bootstrap-vue')['BCardImgLazy']
    BCardText: typeof import('bootstrap-vue')['BCardText']
    BCol: typeof import('bootstrap-vue')['BCol']
    BCollapse: typeof import('bootstrap-vue')['BCollapse']
    BContainer: typeof import('bootstrap-vue')['BContainer']
    BDropdownForm: typeof import('bootstrap-vue')['BDropdownForm']
    BDropdownHeader: typeof import('bootstrap-vue')['BDropdownHeader']
    BEmbed: typeof import('bootstrap-vue')['BEmbed']
    BFormCheckboxGroup: typeof import('bootstrap-vue')['BFormCheckboxGroup']
    BFormInput: typeof import('bootstrap-vue')['BFormInput']
    BFormRating: typeof import('bootstrap-vue')['BFormRating']
    BModal: typeof import('bootstrap-vue')['BModal']
    BNavbar: typeof import('bootstrap-vue')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue')['BNavForm']
    BNavItemDropdown: typeof import('bootstrap-vue')['BNavItemDropdown']
    BPopover: typeof import('bootstrap-vue')['BPopover']
    BRow: typeof import('bootstrap-vue')['BRow']
    HotelCard: typeof import('./src/components/HotelCard.vue')['default']
    HotelCardRating: typeof import('./src/components/HotelCardRating.vue')['default']
    HotelsSection: typeof import('./src/components/HotelsSection.vue')['default']
    MapModal: typeof import('./src/components/modals/MapModal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
